# Generated by Django 5.2.7 on 2025-10-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('priority', models.CharField(max_length=50)),
                ('estimated_hours', models.IntegerField()),
                ('progress', models.IntegerField()),
            ],
        ),
    ]
